---
config:
  axis_x:
    stepper_angle: 1.8
    microstep: 16
    worm_reduction: 144
    gear_small: 20
    gear_big: 40
  axis_y:
    stepper_angle: 1.8
    microstep: 16
    worm_reduction: 144
    gear_small: 20
    gear_big: 40
movement:
  full_rotation_time: 180
system:
  baud: 9600
  fcpu: 16000000
